title: MRC National Survey of Health and Development
description: A website home to the NSHD Metadata and documentation.

theme: just-the-docs

url: https://rmjdish.github.io
baseurl: "/data_dict"


sass:
  load_paths:
    - assets/css

include:
    - assets/css/custom.css    
    - assets/css/table.css    
