title: NSHD Data Dictionary
description: A website home to the NSHD Data Dictionary!
theme: just-the-docs

url: https://rmjdish.github.io/data_dict
baseurl: "/mydocs"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
