title: MRC National Survey of Health and Development
description: A website home to the NSHD Metadata and documentation.
theme: just-the-docs

url: https://rmjdish.github.io
baseurl: "/data_dict"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

sass:
  load_paths:
    - assets/css